queue_rules:
  - name: btest
    batch_size: 2
    merge_conditions:
      - "#approved-reviews-by >= 1"
pull_request_rules:
  - name: queue-to-qbase
    conditions:
      - base = qbase
    actions:
      queue:
        name: btest
