  queue_rules:
    - name: default
      merge_conditions: []
      merge_method: merge
      branch_protection_injection_mode: none

  pull_request_rules:
    - name: queue to main
      conditions:
        - base = main
      actions:
        queue:
          name: default
